"""add unique constraint to garment_type

Revision ID: 8424348fdb21
Revises: 99034f84761b
Create Date: 2025-07-02 13:32:20.437678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8424348fdb21'
down_revision: Union[str, Sequence[str], None] = '99034f84761b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use a batch_alter_table block to support SQLite
    with op.batch_alter_table('garments', schema=None) as batch_op:
        # It's good practice to give your constraint a name
        batch_op.create_unique_constraint("uq_garment_type", ['garment_type'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use a batch_alter_table block for the downgrade as well
    with op.batch_alter_table('garments', schema=None) as batch_op:
        # Use the same constraint name to drop it
        batch_op.drop_constraint("uq_garment_type", type_='unique')

    # ### end Alembic commands ###
