"""Create initial garment tables

Revision ID: 99034f84761b
Revises: 
Create Date: 2025-07-02 13:32:20.437678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99034f84761b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garment_type', sa.String(), nullable=False),
    sa.Column('base_size', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('garment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deltas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement_name', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('delta_value', sa.Float(), nullable=False),
    sa.Column('garment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deltas')
    op.drop_table('base_measurements')
    op.drop_table('garments')
    # ### end Alembic commands ###
